apiVersion: batch/v1
kind: Job
metadata:
  generateName: load-queryservice-ttl
spec:
  template:
    metadata:
      name: load-queryservice-ttl
    spec:
      initContainers:
      - name: export-ttl
        command: ['bash', '-c', 'php /var/www/html/w/extensions/Wikibase/repo/maintenance/dumpRdf.php --output /var/dump/triples.ttl']
        volumeMounts:
        - name: dump-data
          mountPath: /var/dump
      containers:
      - name: import-ttl
        command: ['bash', '-c', 'java -cp lib/wikidata-query-tools-*-jar-with-dependencies.jar org.wikidata.query.rdf.tool.Munge --from /var/dump/triples.ttl --to /tmp/mungeOut/wikidump-%09d.ttl.gz --chunkSize 1 -w ${WBS_DOMAIN} && zcat /tmp/mungeOut/wikidump-*.ttl.gz | curl --silent --show-error -XPOST -H "Content-type:application/x-turtle" --data-binary @- http://queryservice:9999/bigdata/namespace/${WIKI_QS_NAMESPACE}/sparql' ]
        volumeMounts:
        - name: dump-data
          mountPath: /var/dump
      restartPolicy: Never
      volumes:
      - name: dump-data
        emptyDir: {}